# -*- coding: utf-8 -*-
"""AtvBD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1luYScaudfDNOUvllTMmJlnWGQffr3R-D

# Projeto de Banco de Dados - TEMA 2 - Sistema de Gerenciamento de Frota de Veículos

FRANCISCO SÁVIO SOUSA DA CUNHA | MAT. Nº 2025013352

Etapa 7 — ORM acessando o banco criado

"""


# ============================================================
# PARTE 1 — CONFIGURAÇÃO DO PROJETO E CONEXÃO COM O BANCO
# ============================================================

# Importa ferramentas do SQLAlchemy para criar a conexão com o banco
from sqlalchemy import create_engine, text

# String de conexão com o banco PostgreSQL
# Formato: postgresql+driver://usuario:senha@host:porta/banco
DATABASE_URL = "postgresql+psycopg2://postgres:admin@localhost:5432/frota_veiculos" # Mudar usuário e senha conforme sua instação do postgree

# Cria o motor de conexão com o banco
engine = create_engine(DATABASE_URL, echo=False)  # echo=True mostra o SQL gerado

# Testa a conexão executando um comando SQL simples
with engine.connect() as conn:
    r = conn.execute(text("SELECT version();")).fetchone()
print("Conectado!\n", r[0])

"""**Parte 2 — Mapeamento ORM **"""

# ============================================================
# PARTE 2 — MAPEAMENTO ORM (OBJETO → TABELA)
# ============================================================



# Importação de bibliotecas auxiliares
from threading import activeCount
from datetime import date, datetime
import enum
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship, sessionmaker
from sqlalchemy import Integer, String, Numeric, Date, func, ForeignKey, Enum as SQLAlchemyEnum, CheckConstraint, Text, Boolean, text, DateTime # Adicionado DateTime e text


# Classe Base usada por todas as entidades ORM
class Base(DeclarativeBase):
    pass

# ENUM para tipos de veículos
class TipoVeiculoEnum(enum.Enum):
    CARRO = "Carro"
    CAMINHAO = "Caminhão"
    MOTO = "Moto"

# Tabela: tipo_veiculo
class TipoVeiculo(Base):
    __tablename__ = "tipo_veiculo"

    id_tipo_veiculo: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    descricao: Mapped[str] = mapped_column(SQLAlchemyEnum(TipoVeiculoEnum))

    veiculos: Mapped[list["Veiculo"]] = relationship(back_populates="tipo_veiculo")

    def __repr__(self) -> str:
        return f"TipoVeiculo(id_tipo_veiculo={self.id_tipo_veiculo}, descricao={self.descricao!r})"


# ENUM para status de veículos
class StatusVeiculoEnum(enum.Enum):
    ATIVO = "Ativo"
    INATIVO = "Inativo"
    MANUTENCAO = "Em Manutenção"


# Tabela: status_veiculo
class StatusVeiculo(Base):
    __tablename__ = "status_veiculo"
    id_status_veiculo: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    descricao: Mapped[str] = mapped_column(SQLAlchemyEnum(StatusVeiculoEnum))

    veiculos: Mapped[list["Veiculo"]] = relationship(back_populates="status_veiculo")

    def __repr__(self) -> str:
        return f"StatusVeiculo(id_status_veiculo={self.id_status_veiculo}, descricao={self.descricao!r})"


# Tabela: veiculo
class Veiculo(Base):
    __tablename__ = "veiculo"

    id_veiculo: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    placa: Mapped[str] = mapped_column(String(7),nullable=False, unique=True)
    marca: Mapped[str] = mapped_column(String(20), nullable=False)
    modelo: Mapped[str] = mapped_column(String(20), nullable=False)
    ano: Mapped[int] = mapped_column(Integer, nullable=False)
    consumo_medio_padrao: Mapped[float] = mapped_column(Numeric(5,2), nullable=False)
    quilometragem: Mapped[int] = mapped_column(Integer, nullable=False)
    id_tipo_veiculo: Mapped[int] = mapped_column(ForeignKey("tipo_veiculo.id_tipo_veiculo", onupdate='CASCADE', ondelete='RESTRICT'), nullable = False)
    id_status_veiculo: Mapped[int] = mapped_column(ForeignKey("status_veiculo.id_status_veiculo", onupdate='CASCADE', ondelete='RESTRICT'), nullable = False)


    # Relações ORM

    tipo_veiculo: Mapped["TipoVeiculo"] = relationship(back_populates="veiculos")
    status_veiculo: Mapped["StatusVeiculo"] = relationship(back_populates="veiculos")
    abastecimentos: Mapped[list["Abastecimento"]] = relationship(back_populates="veiculo")
    manutencoes: Mapped[list["Manutencao"]] = relationship(back_populates="veiculo")
    alocacoes_viagem: Mapped[list["Alocacao_Viagem"]] = relationship(back_populates="veiculo")

    def __repr__(self) -> str:
        return f'Veiculo(id_veiculo = {self.id_veiculo}, placa = {self.placa!r}, modelo = {self.modelo!r})'


# ENUM para tipo de combustível
class TipoCombustivelEnum(enum.Enum):
    ALCOOL = "Álcool"
    GASOLINA = "Gasolina"
    DIESEL = "Diesel"


# Tabela: abastecimento
class Abastecimento(Base):
    __tablename__ = "abastecimento"

    id_abastecimento: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    placa: Mapped[str] = mapped_column(ForeignKey('veiculo.placa', onupdate='CASCADE', ondelete='RESTRICT'),nullable=False)
    data_abastecimento: Mapped[date] = mapped_column(Date, nullable=False, server_default=func.current_date())
    tipo_combustivel: Mapped[str] = mapped_column(SQLAlchemyEnum(TipoCombustivelEnum))
    litros: Mapped[float] = mapped_column(Numeric(5,2), CheckConstraint('litros > 0'), nullable=False)
    valor_pago: Mapped[float] = mapped_column(Numeric(10,2), CheckConstraint('valor_pago > 0'), nullable=False)
    quilometragem_no_abastecimento: Mapped[int] = mapped_column(Integer, nullable=False)

    # Relação com veículo
    veiculo: Mapped["Veiculo"] = relationship(back_populates="abastecimentos")

    def __repr__(self) -> str:
        return f'Abastecimento(id_abastecimento = {self.id_abastecimento}, placa = {self.placa!r}, litros = {self.litros!r})'

# ENUM para tipo de manutenção
class TipoManutencaoEnum(enum.Enum):
    PREVENTIVA = "Preventiva"
    CORRETIVA = "Corretiva"

# Tabela: manutencao
class Manutencao(Base):
    __tablename__ = "manutencao"

    id_manutencao: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    placa: Mapped[str] = mapped_column(ForeignKey('veiculo.placa', onupdate='CASCADE', ondelete='RESTRICT'),nullable=False)
    data_inicio_manutencao = mapped_column(Date, nullable=False, server_default=func.current_date())
    tipo_manutencao: Mapped[str] = mapped_column(SQLAlchemyEnum(TipoManutencaoEnum))
    data_fim_manutencao = mapped_column(Date,CheckConstraint('data_fim_manutencao >= data_inicio_manutencao'), nullable=True)
    custo_manutencao: Mapped[float] = mapped_column(Numeric(10,2), CheckConstraint('custo_manutencao >= 0'), nullable=False)
    descricao: Mapped[str] = mapped_column(Text, nullable=False)

    # Relacionamento com veiculo
    veiculo: Mapped["Veiculo"] = relationship(back_populates="manutencoes")

    def __repr__(self) -> str:
        return f'Manutencao(id_manutencao = {self.id_manutencao}, placa = {self.placa!r}, tipo_manutencao = {self.tipo_manutencao!r})'


# ENUM para categoria da CNH
class CategoriaCnhEnum(enum.Enum):
    A = "A"
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'

# Tabela: motorista
class Motorista(Base):
    __tablename__ = "motorista"

    id_motorista: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    cpf: Mapped[str] = mapped_column(String(11),nullable=False, unique=True)
    nome: Mapped[str] = mapped_column(String(200), nullable=False)
    categoria_cnh: Mapped[str] = mapped_column(SQLAlchemyEnum(CategoriaCnhEnum))
    data_primeira_habilitacao = mapped_column(Date, nullable=False)
    data_expiracao_cnh = mapped_column(Date, CheckConstraint('data_expiracao_cnh > data_primeira_habilitacao'),nullable=False)
    disponibilidade: Mapped[bool] = mapped_column(Boolean, nullable=False,server_default=text("true"))

    alocacoes_viagem: Mapped[list["Alocacao_Viagem"]] = relationship(back_populates="motorista")

    def __repr__(self) -> str:
        return f'Motorista(id_motorista = {self.id_motorista}, cpf = {self.cpf!r}, nome = {self.nome!r})'


# Tabela: alocacao_viagem
class Alocacao_Viagem(Base):
    __tablename__ = "alocacao_viagem"
    id_viagem: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    placa: Mapped[str] = mapped_column(ForeignKey('veiculo.placa', onupdate='CASCADE', ondelete='RESTRICT'),nullable=False)
    cpf_motorista: Mapped[str] = mapped_column(ForeignKey('motorista.cpf', onupdate='CASCADE', ondelete='RESTRICT'), nullable=False)
    data_saida: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    origem: Mapped[str] = mapped_column(String(100), nullable=False)
    destino: Mapped[str] = mapped_column(String(100), nullable=False)
    data_chegada: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    quilometragem_inicial: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)
    quilometragem_final: Mapped[float] = mapped_column(Numeric(10, 2), nullable=False)

    veiculo: Mapped["Veiculo"] = relationship(back_populates="alocacoes_viagem")
    motorista: Mapped["Motorista"] = relationship(back_populates="alocacoes_viagem")

      # Regras de consistência - constraints do SQL

    __table_args__ = (
        CheckConstraint("data_chegada > data_saida", name="check_datas_viagem"),
        CheckConstraint("quilometragem_inicial >= 0", name="check_km_inicial_positiva"),
        CheckConstraint("quilometragem_final > quilometragem_inicial", name="check_km_consistente"),
    )


    def __repr__(self) -> str:
        return f'Alocacao_Viagem(id_viagem = {self.id_viagem}, placa = {self.placa!r}, cpf_motorista = {self.cpf_motorista!r})'

# Criação das tabelas no banco
Base.metadata.drop_all(engine) # Remove as tabelas
Base.metadata.create_all(engine) # Recria as tabelas
print("Tabelas criadas!")

# Criação da sessão ORM

SessionLocal = sessionmaker(bind=engine)

with SessionLocal() as session:
    print("Session aberta e pronta.")

"""**Parte 3 — Operações CRUD via ORM**"""

# ============================================================
# PARTE 3 — OPERAÇÕES CRUD
# ============================================================

# CRUD = Create, Read, Update, Delete


from sqlalchemy import select


# --- Funções CREATE - Criar registros

def criar_tipo_veiculo(session, descricao: str) -> TipoVeiculo:
    tipo = TipoVeiculo(descricao=descricao)
    session.add(tipo)
    session.commit()
    session.refresh(tipo)
    return tipo

def criar_status_veiculo(session, descricao: str) -> StatusVeiculo:
    status = StatusVeiculo(descricao=descricao)
    session.add(status)
    session.commit()
    session.refresh(status)
    return status

def criar_veiculo(session, placa: str, marca: str, modelo: str, ano: int, consumo_medio_padrao: float, quilometragem: int, id_tipo_veiculo: int, id_status_veiculo: int) -> Veiculo:
    veiculo = Veiculo(placa=placa, marca=marca, modelo=modelo, ano=ano, consumo_medio_padrao=consumo_medio_padrao, quilometragem=quilometragem, id_tipo_veiculo=id_tipo_veiculo, id_status_veiculo=id_status_veiculo)
    session.add(veiculo)
    session.commit()
    session.refresh(veiculo)
    return veiculo

def criar_abastecimento(session, placa: str, data_abastecimento: date,tipo_combustivel: str, litros: float, valor_pago: float, quilometragem_no_abastecimento: int) -> Abastecimento:
    abastecimento = Abastecimento(placa=placa, data_abastecimento=data_abastecimento, tipo_combustivel=tipo_combustivel, litros=litros, valor_pago=valor_pago, quilometragem_no_abastecimento=quilometragem_no_abastecimento)
    session.add(abastecimento)
    session.commit()
    session.refresh(abastecimento)
    return abastecimento

def criar_manutencao(session, placa: str, data_inicio_manutencao: date, tipo_manutencao: str, data_fim_manutencao: date, custo_manutencao: float, descricao: str) -> Manutencao:
    manutencao = Manutencao(placa=placa, data_inicio_manutencao=data_inicio_manutencao, tipo_manutencao=tipo_manutencao, data_fim_manutencao=data_fim_manutencao, custo_manutencao=custo_manutencao, descricao=descricao)
    session.add(manutencao)
    session.commit()
    session.refresh(manutencao)
    return manutencao

def criar_motorista(session, cpf: str, nome: str, categoria_cnh: str, data_primeira_habilitacao: date, data_expiracao_cnh: date, disponibilidade: bool = True) -> Motorista:
    motorista = Motorista(cpf=cpf, nome=nome, categoria_cnh=categoria_cnh, data_primeira_habilitacao=data_primeira_habilitacao, data_expiracao_cnh=data_expiracao_cnh, disponibilidade=disponibilidade)
    session.add(motorista)
    session.commit()
    session.refresh(motorista)
    return motorista

def criar_alocacao_viagem(session, placa: str, cpf_motorista: str, data_saida: datetime, origem: str, destino: str, data_chegada: datetime, quilometragem_inicial: float, quilometragem_final: float) -> Alocacao_Viagem:
    alocacao = Alocacao_Viagem(placa=placa, cpf_motorista=cpf_motorista, data_saida=data_saida, origem=origem, destino=destino, data_chegada=data_chegada, quilometragem_inicial=quilometragem_inicial, quilometragem_final=quilometragem_final)
    session.add(alocacao)
    session.commit()
    session.refresh(alocacao)
    return alocacao


# --- Funções CRUD ---

# READ (Listagem com paginação e ordenação)
def listar_veiculos(session, offset: int = 0, limit: int = 10, order_by: str = 'placa'):
    """Lista veículos com paginação e ordenação."""
    # Mapeia a string de order_by para o atributo do modelo Veiculo
    order_attribute = getattr(Veiculo, order_by, Veiculo.placa)

    veiculos = session.scalars(select(Veiculo).order_by(order_attribute).offset(offset).limit(limit)).all()
    return veiculos

# UPDATE (Atualização)
def atualizar_quilometragem_veiculo(session, placa: str, nova_quilometragem: int) -> Veiculo | None:
    """Atualiza a quilometragem de um veículo."""
    veiculo = session.scalar(select(Veiculo).filter_by(placa=placa))
    if veiculo:
        veiculo.quilometragem = nova_quilometragem
        session.commit()
        session.refresh(veiculo)
    return veiculo

def desativar_veiculo(session, placa: str):
    """Desativa um veículo (soft delete)."""
    veiculo = session.scalar(select(Veiculo).filter_by(placa=placa))
    if veiculo:
        # Obter o id do status 'INATIVO'
        status_inativo = session.scalar(select(StatusVeiculo).filter_by(descricao=StatusVeiculoEnum.INATIVO))
        if status_inativo:
            veiculo.id_status_veiculo = status_inativo.id_status_veiculo
            session.commit()
            session.refresh(veiculo)
        else:
            print(f"Status 'INATIVO' não encontrado. Não foi possível desativar o veículo {placa}.")
    return veiculo

def remover_veiculo_fisicamente(session, placa: str):
    """Remove um veículo fisicamente do banco de dados (hard delete)."""
    veiculo = session.scalar(select(Veiculo).filter_by(placa=placa))
    if veiculo:
        session.delete(veiculo)
        session.commit()
        print(f"Veículo com placa {placa} removido fisicamente.")
    else:
        print(f"Veículo com placa {placa} não encontrado.")



# --- Inserção de dados no banco ---
with engine.connect() as conn:
    # Populando a tabela: tipo_veiculo
    conn.execute(text("INSERT INTO tipo_veiculo (descricao) VALUES ('CARRO'), ('CAMINHAO'), ('MOTO');"))

    # Populando a tabela: Status_Veiculo
    conn.execute(text("INSERT INTO status_veiculo (descricao) VALUES ('ATIVO'), ('MANUTENCAO'), ('INATIVO');"))

    # Populando a tabela: Veiculo
    conn.execute(text("INSERT INTO veiculo (placa, marca, modelo, ano, consumo_medio_padrao, quilometragem, id_tipo_veiculo, id_status_veiculo) VALUES ('ABC1234', 'Fiat', 'Toro', 2021, 10.50, 45000.00, 1, 1), ('XYZ9876', 'Volvo', 'FH', 2019, 5.00, 150000.00, 2, 2), ('MOT5555', 'Honda', 'BROS', 2022, 28.00, 12000.00, 3, 1),('CAR7777', 'Chevrolet', 'Onix', 2023, 12.00, 5000.00, 1, 3);"))

    # Populando a tabela: Motorista
    conn.execute(text("INSERT INTO motorista (cpf, nome, categoria_cnh, data_primeira_habilitacao, data_expiracao_cnh, disponibilidade) VALUES ('12345678901', 'Antonio Pedro Cunha', 'B', '2018-05-10', '2028-05-10', true),('98765432100', 'Maria Joana Silva', 'E', '2015-10-20', '2025-10-20', true),('45678912300', 'Francisco Jose Sousa','A', '2021-01-15', '2031-01-15', false), ('32165498700', 'Pedro Ferreira Inacio','C', '2010-03-30', '2030-03-30', true);"))

    # Populando a tabela: Abastecimento
    conn.execute(text("INSERT INTO abastecimento (placa, data_abastecimento, tipo_combustivel, litros, valor_pago, quilometragem_no_abastecimento) VALUES ('ABC1234', '2026-01-05', 'GASOLINA', 45.00, 270.00, 45100.00),('XYZ9876', '2026-01-06', 'DIESEL', 200.00, 1000.00, 150500.00),('MOT5555', '2026-02-09', 'GASOLINA', 10.00, 50.00, 12050.00);"))

    # Populando a tabela: Manutenção
    conn.execute(text("INSERT INTO manutencao (placa, data_inicio_manutencao, tipo_manutencao, data_fim_manutencao, custo_manutencao, descricao) VALUES ('XYZ9876', '2026-01-20', 'CORRETIVA', '2026-02-10', 2500.00, 'Troca de embreagem e revisão de freios'),('MOT5555', '2026-02-08', 'PREVENTIVA', '2026-02-08', 30.00, 'Troca de óleo e calibragem dos pneus'),('CAR7777', '2026-02-09', 'PREVENTIVA', '2026-02-09', 400.00, 'Troca de óleo');"))

    # Populando a tabela: Alocação_Viagem
    conn.execute(text("INSERT INTO alocacao_viagem (placa, cpf_motorista, data_saida, origem, destino, data_chegada, quilometragem_inicial, quilometragem_final) VALUES ('CAR7777','32165498700', '2025-12-10 07:30:00', 'Fortaleza', 'Itapipoca', '2025-12-10 10:30:00', 5000.00, 5150.00),('ABC1234', '12345678901', '2025-12-12 08:00:00', 'Sobral', 'Fortaleza', '2025-12-12 11:30:00', 45000.00, 45250.00),('MOT5555', '45678912300', '2026-02-05 14:00:00', 'Itapipoca', 'Umirim', '2026-02-05 14:45:00', 12050.00, 12190.00);"))

    conn.commit()
    print("Dados inseridos com sucesso!")

# --- Demonstração CRUD ---
with SessionLocal() as session:
    print("--- Criando Tipos de Veículo ---")
    carro = criar_tipo_veiculo(session, TipoVeiculoEnum.CARRO)
    caminhao = criar_tipo_veiculo(session, TipoVeiculoEnum.CAMINHAO)
    moto = criar_tipo_veiculo(session, TipoVeiculoEnum.MOTO)
    print("Tipos de Veículo criados:", carro, caminhao, moto)

    print("\n--- Criando Status de Veículo ---")
    ativo = criar_status_veiculo(session, StatusVeiculoEnum.ATIVO)
    inativo = criar_status_veiculo(session, StatusVeiculoEnum.INATIVO)
    manutencao = criar_status_veiculo(session, StatusVeiculoEnum.MANUTENCAO)
    print("Status de Veículo criados:", ativo, inativo, manutencao)

    print("\n--- Criando Veículos (3 registros) ---")
    veiculo_a = criar_veiculo(session, "NEW1111", "Toyota", "Corolla", 2022, 11.5, 15000, carro.id_tipo_veiculo, ativo.id_status_veiculo)
    veiculo_b = criar_veiculo(session, "NEW2222", "Scania", "R450", 2021, 4.0, 200000, caminhao.id_tipo_veiculo, ativo.id_status_veiculo)
    veiculo_c = criar_veiculo(session, "NEW3333", "Yamaha", "Factor", 2023, 35.0, 5000, moto.id_tipo_veiculo, manutencao.id_status_veiculo)
    print("Veículos criados:", veiculo_a, veiculo_b, veiculo_c)

    print("\n--- Listando Veículos (Ordenados por placa, 2 por página) ---")
    veiculos_pag1 = listar_veiculos(session, offset=0, limit=2, order_by='placa')
    print("Página 1:", veiculos_pag1)
    veiculos_pag2 = listar_veiculos(session, offset=2, limit=2, order_by='placa')
    print("Página 2:", veiculos_pag2)

    print("\n--- Atualizando Veículo (Quilometragem) ---")
    veiculo_atualizado = atualizar_quilometragem_veiculo(session, veiculo_a.placa, 20000)
    print(f"Veículo {veiculo_a.placa} quilometragem atualizada para {veiculo_atualizado.quilometragem} km")

    print("\n--- Removendo Veículo (Soft Delete) ---")
    veiculo_desativado = desativar_veiculo(session, veiculo_c.placa)
    if veiculo_desativado:
        status_descricao = session.scalar(select(StatusVeiculo).filter_by(id_status_veiculo=veiculo_desativado.id_status_veiculo)).descricao
        print(f"Veículo {veiculo_c.placa} desativado. Novo status: {status_descricao}")

    print("\n--- Listando Veículos Novamente ---")
    todos_veiculos = listar_veiculos(session, limit=None) # Listar todos
    for v in todos_veiculos:
        status_obj = session.scalar(select(StatusVeiculo).filter_by(id_status_veiculo=v.id_status_veiculo))
        print(f"Placa: {v.placa}, Modelo: {v.modelo}, KM: {v.quilometragem}, Status: {status_obj.descricao}")

    print("\n--- Criando Motorista e Abastecimento ---")
    motorista = criar_motorista(session, "11122233344", "Novo Motorista", CategoriaCnhEnum.C, date(2019, 1, 1), date(2029, 1, 1))
    abastecimento = criar_abastecimento(session, veiculo_a.placa, date(2024, 6, 1), TipoCombustivelEnum.GASOLINA, 40.0, 250.00, 20100)
    print("Motorista criado:", motorista)
    print("Abastecimento criado:", abastecimento)

    print("\n--- Removendo Veículo (Hard Delete - exemplo) ---")
    abastecimento_removido = session.scalar(select(Abastecimento).filter_by(placa=veiculo_a.placa))
    if abastecimento_removido:
        session.delete(abastecimento_removido)
        session.commit()
        print(f"Abastecimento do veículo {veiculo_a.placa} removido antes do hard delete.")

    remover_veiculo_fisicamente(session, veiculo_a.placa)

    print("\n--- Verificando se o Veículo foi removido ---")
    verificar_veiculo = session.scalar(select(Veiculo).filter_by(placa=veiculo_a.placa))
    if verificar_veiculo is None:
        print(f"Veículo {veiculo_a.placa} não encontrado no banco de dados após a remoção física.")
    else:
        print(f"Veículo {veiculo_a.placa} ainda está presente: {verificar_veiculo}")


"""**Parte 4 — Consultas com relacionamento **"""

# Exemplos de consultas usando JOIN e filtros

from sqlalchemy import select

with SessionLocal() as session:
    print("\n--- Consultas ORM com Relacionamentos e Filtros ---")

    # Consulta 1: Listar veículos e suas descrições de tipo e status (equivalente a JOIN)
    print("\n1. Veículos com Tipo e Status:\n")
    veiculos_com_detalhes = session.query(Veiculo, TipoVeiculo, StatusVeiculo).\
        join(TipoVeiculo, Veiculo.id_tipo_veiculo == TipoVeiculo.id_tipo_veiculo).\
        join(StatusVeiculo, Veiculo.id_status_veiculo == StatusVeiculo.id_status_veiculo).\
        all()
    for veiculo, tipo, status in veiculos_com_detalhes:
        print(f"Placa: {veiculo.placa}, Marca: {veiculo.marca}, Modelo: {veiculo.modelo}, Tipo: {tipo.descricao.value}, Status: {status.descricao.value}")

    # Consulta 2: Listar motoristas e suas viagens alocadas (filtrando por atributo de tabela relacionada)
    print("\n2. Motoristas e suas Viagens Alocadas:\n")
    motoristas_com_viagens = session.query(Motorista).\
        join(Alocacao_Viagem, Motorista.cpf == Alocacao_Viagem.cpf_motorista).\
        order_by(Motorista.nome).\
        all()

    # Para evitar duplicações se um motorista tiver várias viagens, podemos usar um set ou group by
    unique_motoristas_com_viagens = session.query(Motorista).\
        join(Alocacao_Viagem, Motorista.cpf == Alocacao_Viagem.cpf_motorista).\
        group_by(Motorista.id_motorista).\
        order_by(Motorista.nome).\
        all()

    for motorista in unique_motoristas_com_viagens:
        print(f"Motorista: {motorista.nome} (CPF: {motorista.cpf})")
        for viagem in motorista.alocacoes_viagem:
            print(f"  - Viagem: {viagem.origem} -> {viagem.destino} (Veículo: {viagem.placa})")

    # Consulta 3: Top 3 veículos ativos com maior quilometragem (filtro + ordenação)
    print("\n3. Top 3 Veículos Ativos por Quilometragem:\n")
    # Primeiro, encontrar o id do status 'ATIVO'
    status_ativo_id = session.scalar(select(StatusVeiculo.id_status_veiculo).filter_by(descricao=StatusVeiculoEnum.ATIVO))

    if status_ativo_id:
        top_veiculos = session.query(Veiculo).\
            filter(Veiculo.id_status_veiculo == status_ativo_id).\
            order_by(Veiculo.quilometragem.desc()).\
            limit(3).\
            all()

        for veiculo in top_veiculos:
            print(f"Placa: {veiculo.placa}, Modelo: {veiculo.modelo}, Quilometragem: {veiculo.quilometragem} km")
    else:
        print("Status 'ATIVO' não encontrado.")

    print("\n--- Consultas Concluídas ---")